/*

 LEVEL6.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 14
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8Lisboa1755!


*/

#define level6Width 21
#define level6Height 13
#define level6Bank 0

extern unsigned char level6[];

/* End of LEVEL6.H */
