/*

 LEVEL3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 14
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level3Width 25
#define level3Height 14
#define level3Bank 0

extern unsigned char level3[];

/* End of LEVEL3.H */
