/*

 LEVEL11.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 29 x 18
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8Lisboa1755!


*/

#define level8Width 29
#define level8Height 19
#define level8Bank 0

extern unsigned char level11[];

/* End of LEVEL11.H */
