/*

 LEVEL5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 14
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8Lisboa1755!


*/

#define level5Width 22
#define level5Height 14
#define level5Bank 0

extern unsigned char level5[];

/* End of LEVEL5.H */
