/*

 BLANKSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BlankScreenWidth 20
#define BlankScreenHeight 18
#define BlankScreenBank 0

extern unsigned char BlankScreen[];

/* End of BLANKSCREEN.H */
