/*

 LEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 14
   Tile set      : C:\Users\ivpereira\Downloads\gbtb\blockdude-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level2Width 20
#define Level2Height 14
#define Level2Bank 0

extern unsigned char Level2[];

/* End of LEVEL2.H */
