/*

 TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Tiles[] =
{
  0x3C,0x3C,0xFE,0xFE,0x32,0x32,0x42,0x42,
  0x24,0x24,0x5A,0x5A,0x18,0x18,0x66,0x66
};

/* End of TILES.C */
